# Generated by Django 4.1.1 on 2022-09-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='img',
            field=models.ImageField(null=True, upload_to='img/', verbose_name='изображение'),
        ),
    ]
