# Generated by Django 4.1.1 on 2022-09-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_discount_tax_alter_items_img_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
