# Generated by Django 4.1.1 on 2022-09-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_rename_name_discount_coupon_alter_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='sale',
            field=models.IntegerField(blank=True, default=1, verbose_name='Скидка в процентах'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='tax',
            field=models.IntegerField(blank=True, default=1, verbose_name='Налог в процентах'),
        ),
    ]
