# Generated by Django 4.1.1 on 2022-09-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_discount_sale_alter_tax_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='currency',
            field=models.CharField(choices=[('rub', 'Rub'), ('usd', 'Usd'), ('eur', 'Eur')], default='rub', max_length=255),
        ),
        migrations.AlterField(
            model_name='tax',
            name='tax',
            field=models.IntegerField(blank=True, default=0, verbose_name='Налог в процентах'),
        ),
    ]
